// cmd/docgen generates a Markdown compatibility matrix from conduit Descriptors.
//
// Usage:
//
//	go run ./cmd/docgen -out docs/conduit-capabilities.md
//
// When adding a new conduit package, import it here and append its
// Descriptor to the `descriptors` slice.
package main

import (
	"flag"
	"fmt"
	"log/slog"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/andrewhowdencom/ore/conduit"
	"github.com/andrewhowdencom/ore/conduit/tui"
)

// descriptors is the explicit list of conduit descriptors to document.
// Future descriptors are added here when they are implemented.
var descriptors = []conduit.Descriptor{
	tui.Descriptor,
}

func main() {
	out := flag.String("out", "docs/conduit-capabilities.md", "output markdown file path")
	title := flag.String("title", "Conduit Capability Matrix", "markdown document title")
	flag.Parse()

	logger := slog.New(slog.NewTextHandler(os.Stderr, nil))

	if err := run(*out, *title); err != nil {
		logger.Error("docgen failed", "err", err)
		os.Exit(1)
	}

	logger.Info("generated capability matrix", "path", *out)
}

func run(outPath, title string) error {
	// Collect all unique capabilities.
	capSet := make(map[conduit.Capability]struct{})
	for _, desc := range descriptors {
		for _, cap := range desc.Capabilities {
			capSet[cap] = struct{}{}
		}
	}

	caps := make([]conduit.Capability, 0, len(capSet))
	for cap := range capSet {
		caps = append(caps, cap)
	}
	sort.Slice(caps, func(i, j int) bool {
		return caps[i] < caps[j]
	})

	// Build markdown.
	var b strings.Builder
	b.WriteString("<!-- Generated by cmd/docgen. Do not edit manually. -->\n\n")
	b.WriteString("# ")
	b.WriteString(title)
	b.WriteString("\n\n")
	b.WriteString("This matrix shows which capabilities each conduit implementation supports.\n\n")

	// Header row.
	b.WriteString("| Capability |")
	for _, desc := range descriptors {
		b.WriteString(" ")
		b.WriteString(desc.Name)
		b.WriteString(" |")
	}
	b.WriteString("\n")

	// Separator row.
	b.WriteString("|------------|")
	for range descriptors {
		b.WriteString("----------|")
	}
	b.WriteString("\n")

	// Data rows.
	for _, cap := range caps {
		b.WriteString("| ")
		b.WriteString(string(cap))
		b.WriteString(" |")
		for _, desc := range descriptors {
			b.WriteString(" ")
			if contains(desc.Capabilities, cap) {
				b.WriteString("✅")
			} else {
				b.WriteString("❌")
			}
			b.WriteString(" |")
		}
		b.WriteString("\n")
	}

	// Write to file.
	if err := os.MkdirAll(filepath.Dir(outPath), 0755); err != nil {
		return fmt.Errorf("create output directory: %w", err)
	}
	if err := os.WriteFile(outPath, []byte(b.String()), 0644); err != nil {
		return fmt.Errorf("write output file: %w", err)
	}

	return nil
}

func contains(caps []conduit.Capability, cap conduit.Capability) bool {
	for _, c := range caps {
		if c == cap {
			return true
		}
	}
	return false
}
